# Generated by Django 5.2.10 on 2026-07-19 11:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdukRingkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, help_text='SKU internal, mis. PK00229. Boleh kosong dulu.', max_length=30, null=True, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('kemasan', models.CharField(default='-', help_text='Varian kemasan fisik: PAIL 25KG, DUS 12KG, GALON, PCS, dst.', max_length=50)),
                ('uom', models.CharField(default='UNIT', help_text='Satuan output packaging: UNIT, DUS, BOTOL, dst.', max_length=20)),
                ('stok_minimum', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ambang alert restock barang jadi (per varian kemasan).', max_digits=15)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produk (sementara)',
                'verbose_name_plural': 'Produk (sementara)',
                'ordering': ['nama', 'kemasan'],
                'constraints': [models.UniqueConstraint(fields=('nama', 'kemasan'), name='produk_unik_per_kemasan')],
            },
        ),
        migrations.CreateModel(
            name='FormulaProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versi', models.PositiveIntegerField(default=1)),
                ('aktif', models.BooleanField(default=True)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formula', to='produksi.produkringkas')),
            ],
            options={
                'verbose_name': 'Formula Produk',
                'verbose_name_plural': 'Formula Produk',
                'ordering': ['produk', '-versi'],
            },
        ),
        migrations.CreateModel(
            name='SesiProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DIBUKA', 'Dibuka'), ('DITUTUP', 'Ditutup (rekonsiliasi terkunci)')], db_index=True, default='DIBUKA', max_length=10)),
                ('catatan', models.TextField(blank=True)),
                ('dibuka_pada', models.DateTimeField(auto_now_add=True)),
                ('ditutup_pada', models.DateTimeField(blank=True, null=True)),
                ('dibuka_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesi_dibuka', to=settings.AUTH_USER_MODEL)),
                ('ditutup_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesi_ditutup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesi Produksi',
                'verbose_name_plural': 'Sesi Produksi',
                'ordering': ['-dibuka_pada'],
            },
        ),
        migrations.CreateModel(
            name='RekonsiliasiBaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=150)),
                ('uom', models.CharField(default='KG', max_length=20)),
                ('qty_setoran', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('qty_pemakaian', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Alloc_i (desimal) x beta_m — bahan yang terkandung di produk jatah entitas ini.', max_digits=15)),
                ('qty_sisa', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Net_im = C_im - (Alloc_i x beta_m). Boleh minus.', max_digits=15)),
                ('nilai_net', models.DecimalField(blank=True, decimal_places=2, help_text='V_im = Net_im x P_m (harga dari master bahan). Null kalau harga belum diisi.', max_digits=18, null=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rekonsiliasi_baris', to='entitas.akun')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rekonsiliasi', to='produksi.sesiproduksi')),
            ],
            options={
                'verbose_name': 'Rekonsiliasi (baris)',
                'verbose_name_plural': 'Rekonsiliasi (baris)',
            },
        ),
        migrations.CreateModel(
            name='HasilPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('no_batch_fg', models.CharField(db_index=True, max_length=50)),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('dicatat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_dicatat', to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hasil_packaging', to='produksi.produkringkas')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hasil_packaging', to='produksi.sesiproduksi')),
            ],
            options={
                'verbose_name': 'Hasil Packaging',
                'verbose_name_plural': 'Hasil Packaging',
                'ordering': ['-dicatat_pada'],
            },
        ),
        migrations.CreateModel(
            name='AlokasiProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=6, help_text='Porsi kepemilikan (0-1).', max_digits=9)),
                ('alloc_desimal', models.DecimalField(decimal_places=4, max_digits=15)),
                ('alloc_unit', models.DecimalField(decimal_places=2, help_text='Hasil pembulatan LRM.', max_digits=15)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alokasi_produk', to='entitas.akun')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alokasi_produk', to='produksi.produkringkas')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alokasi_produk', to='produksi.sesiproduksi')),
            ],
            options={
                'verbose_name': 'Alokasi Produk',
                'verbose_name_plural': 'Alokasi Produk',
            },
        ),
        migrations.CreateModel(
            name='SetoranBahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=150)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('uom', models.CharField(default='KG', max_length=20)),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setoran_bahan', to='entitas.akun')),
                ('dicatat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setoran_dicatat', to=settings.AUTH_USER_MODEL)),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setoran', to='produksi.sesiproduksi')),
            ],
            options={
                'verbose_name': 'Setoran Bahan',
                'verbose_name_plural': 'Setoran Bahan',
                'ordering': ['-dicatat_pada'],
            },
        ),
        migrations.CreateModel(
            name='KomposisiFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(help_text='Harus sama persis dengan nama di stock_raw.', max_length=150)),
                ('qty_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('uom', models.CharField(default='KG', max_length=20)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komposisi', to='produksi.formulaproduk')),
            ],
            options={
                'verbose_name': 'Komposisi Formula',
                'verbose_name_plural': 'Komposisi Formula',
                'constraints': [models.UniqueConstraint(fields=('formula', 'nama_bahan'), name='komposisi_unik_per_bahan'), models.CheckConstraint(condition=models.Q(('qty_per_unit__gt', 0)), name='komposisi_qty_positif')],
            },
        ),
        migrations.AddConstraint(
            model_name='formulaproduk',
            constraint=models.UniqueConstraint(fields=('produk', 'versi'), name='formula_unik_per_versi'),
        ),
        migrations.AddConstraint(
            model_name='rekonsiliasibaris',
            constraint=models.UniqueConstraint(fields=('sesi', 'akun', 'nama_bahan'), name='rekonsiliasi_unik'),
        ),
        migrations.AddConstraint(
            model_name='hasilpackaging',
            constraint=models.CheckConstraint(condition=models.Q(('qty_unit__gt', 0)), name='packaging_qty_positif'),
        ),
        migrations.AddConstraint(
            model_name='alokasiproduk',
            constraint=models.UniqueConstraint(fields=('sesi', 'akun'), name='alokasi_unik_per_akun'),
        ),
        migrations.AddConstraint(
            model_name='setoranbahan',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='setoran_qty_positif'),
        ),
    ]
