# Generated by Django 5.2.10 on 2026-07-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_tanki_jenis'),
        ('produksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilpackaging',
            name='dari_tanki',
            field=models.ForeignKey(blank=True, help_text='Tanki sumber (hanya jenis MIXING/BLENDING). Jejak fisik — tidak memengaruhi perhitungan Share/Net.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hasil_packaging', to='inventory.tanki'),
        ),
    ]
