# Generated by Django 5.2.10 on 2026-07-19 11:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitas', '0001_initial'),
        ('produksi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('kode', models.CharField(help_text='Kode internal, mis. ALT-001.', max_length=30, unique=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('kondisi', models.CharField(choices=[('BAIK', 'Baik'), ('PERBAIKAN', 'Sedang diperbaiki'), ('RUSAK', 'Rusak')], default='BAIK', max_length=15)),
                ('lokasi', models.CharField(blank=True, help_text="Mis. 'Ruang mixing', 'Rak B2'.", max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True, help_text='Nonaktifkan (jangan hapus) kalau sudah tidak dipakai.')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alat',
                'verbose_name_plural': 'Alat',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Tanki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Mis. TK-01.', max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('PENAMPUNG_GILING', 'Tanki penampungan hasil giling'), ('MIXING', 'Tanki mixing'), ('SIMPAN', 'Tanki simpan lainnya')], max_length=20)),
                ('kapasitas', models.DecimalField(blank=True, decimal_places=2, help_text='Kapasitas maksimum (opsional, satuan uom_kapasitas).', max_digits=15, null=True)),
                ('uom_kapasitas', models.CharField(default='KG', max_length=20)),
                ('keterangan', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tanki',
                'verbose_name_plural': 'Tanki',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='MutasiBarangJadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('MASUK_PRODUKSI', 'Masuk dari produksi'), ('KELUAR_PENJUALAN', 'Keluar penjualan/distribusi'), ('ALOKASI_RETAIL', 'Keluar alokasi ke toko retail'), ('RETUR_RETAIL', 'Masuk retur dari toko retail'), ('KOREKSI', 'Koreksi / stock opname')], db_index=True, max_length=25)),
                ('no_batch', models.CharField(blank=True, max_length=50)),
                ('qty_unit', models.DecimalField(decimal_places=2, help_text='Positif masuk, negatif keluar.', max_digits=15)),
                ('referensi', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_barang_jadi', to='entitas.akun')),
                ('dicatat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_fg_dicatat', to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_barang_jadi', to='produksi.produkringkas')),
            ],
            options={
                'verbose_name': 'Mutasi Barang Jadi',
                'verbose_name_plural': 'Mutasi Barang Jadi',
                'ordering': ['-dicatat_pada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BatchBarangJadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_batch', models.CharField(db_index=True, max_length=50)),
                ('qty_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_barang_jadi', to='entitas.akun')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_barang_jadi', to='produksi.produkringkas')),
                ('sesi_asal', models.ForeignKey(blank=True, help_text='Kosong kalau masuk bukan dari produksi (mis. koreksi opname).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_barang_jadi', to='produksi.sesiproduksi')),
            ],
            options={
                'verbose_name': 'Batch Barang Jadi',
                'verbose_name_plural': 'Batch Barang Jadi',
                'ordering': ['produk', 'dibuat_pada'],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_unit__gte', 0)), name='fg_qty_tidak_minus'), models.UniqueConstraint(fields=('produk', 'pemilik', 'no_batch'), name='fg_unik_per_pemilik_batch')],
            },
        ),
        migrations.CreateModel(
            name='IsiTanki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(db_index=True, max_length=150)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('uom', models.CharField(default='KG', max_length=20)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('sesi_asal', models.ForeignKey(blank=True, help_text='Sesi terakhir yang menaruh sisa ke sini.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='isi_tanki', to='produksi.sesiproduksi')),
                ('tanki', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isi', to='inventory.tanki')),
            ],
            options={
                'verbose_name': 'Isi Tanki',
                'verbose_name_plural': 'Isi Tanki',
                'ordering': ['tanki', 'nama_bahan'],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='isi_tanki_tidak_minus'), models.UniqueConstraint(fields=('tanki', 'nama_bahan'), name='isi_tanki_unik_per_bahan')],
            },
        ),
    ]
