# Generated by Django 5.2.10 on 2026-07-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanki',
            name='jenis',
            field=models.CharField(choices=[('PENAMPUNG_GILING', 'Tanki penampungan hasil giling'), ('MIXING', 'Tanki hasil mixing'), ('BLENDING', 'Tanki hasil blending'), ('SIMPAN', 'Tanki simpan lainnya')], max_length=20),
        ),
    ]
